version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=polaire
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: ./polaire
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./polaire:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  angular:
    build: ./angular
    command: sh -c "npm install && ng serve --host=0.0.0.0 --sourceMap=false --no-live-reload"
    volumes:
      - ./angular:/code
    ports:
      - "4200:4200"
  nginx-proxy:
    build: nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - vhost:/etc/nginx/vhost.d

    depends_on:
      - django
      - angular

volumes:
  vhost: