# syntax=docker/dockerfile:1
FROM polaire-basedependencies:latest

COPY .. /code

#python dependencies
WORKDIR /code
RUN pipenv install --system --deploy --ignore-pipfile

#node dependencies
WORKDIR /code/polaire/angular
RUN npm install

#database creation
WORKDIR /code/polaire
ENV DJANGO_SETTINGS_MODULE=polaire.settings
RUN python ./manage.py migrate
RUN python -c "import django;django.setup();from django.contrib.auth.models import User;User.objects.create_superuser('admin', 'admin@polaire.com', 'admin')" 
#standard user/pw: admin/admin            please change in all environments

#entry
WORKDIR /code
EXPOSE 8000
CMD pipenv install --system --deploy --ignore-pipfile; npm install --prefix ./polaire/angular ./polaire/angular

