# Generated by Django 3.1.7 on 2021-04-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='reference',
        ),
        migrations.AddField(
            model_name='company',
            name='business',
            field=models.CharField(choices=[('Fotograf', 'Fotograf'), ('Visagist', 'Visagist'), ('Drohnenpilot', 'Drohnenpilot'), ('DJs', 'DJs'), ('Model', 'Model'), ('Catering', 'Catering'), ('Sonstige', 'Sonstige')], default='Sonstige', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('EPU', 'Ein Personen Unternehmen'), ('KMU', 'Klein und Mittel Unternehmen'), ('SU', 'StartUp')], default='EPU', max_length=3),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('m', 'Herr'), ('f', 'Frau'), ('n', 'Nicht spezifizert')], default='o', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='title_first',
            field=models.CharField(choices=[('none', ''), ('Mag.', 'Magister'), ('Dr.', 'Doctor'), ('Ing.', 'Ingineur'), ('Dipl. Ing.', 'Diplomingineur'), ('Prof.', 'Professor'), ('Sonstiges', 'StartUp')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='title_last',
            field=models.CharField(choices=[('none', ''), ('BA', 'Bachelor of Arts, Bachelor of Education'), ('BEng', 'Bachelor of Engineering'), ('BSc', 'Bachelor of Science'), ('MBA', 'Master of Business Administration'), ('MSc', 'Master of Science'), ('LLB', 'Ingineur'), ('BSC', 'Diplomingineur'), ('LLM', 'Professor'), ('Sonstiges', 'StartUp')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='works_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mail',
            field=models.CharField(max_length=40),
        ),
    ]
