# Generated by Django 3.1.7 on 2021-04-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210402_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.CharField(default='lgo', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.CharField(default='pic', max_length=128),
            preserve_default=False,
        ),
    ]
