# Generated by Django 3.2.3 on 2021-05-16 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210516_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='adress',
        ),
        migrations.AddField(
            model_name='adress',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.company', verbose_name='Company'),
        ),
    ]
