# Generated by Django 3.2.3 on 2021-05-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210516_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.company', unique=True, verbose_name='Company'),
        ),
    ]
