# Generated by Django 3.2.3 on 2021-05-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_adress_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='works_at',
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.company', unique=True, verbose_name='Company'),
        ),
    ]
