# Generated by Django 3.2.3 on 2021-09-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_module_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='attributes',
            new_name='content',
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('gallery', 'gallery'), ('picture', 'picture'), ('sozial', 'sozial'), ('collage', 'collage')], default='o', max_length=10),
        ),
    ]
