# Generated by Django 3.2.7 on 2021-09-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210902_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='postal',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adress',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='link_social_media',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Not Spezified')], default='n', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_first',
            field=models.CharField(choices=[('none', ''), ('Mag.', 'Magister'), ('Dr.', 'Doctor'), ('Ing.', 'Ingineur'), ('Dipl. Ing.', 'Diplomingineur'), ('Prof.', 'Professor'), ('Sonstiges', 'Very Important')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='title_last',
            field=models.CharField(choices=[('none', ''), ('BA', 'Bachelor of Arts, Bachelor of Education'), ('BEng', 'Bachelor of Engineering'), ('BSc', 'Bachelor of Science'), ('MBA', 'Master of Business Administration'), ('MSc', 'Master of Science'), ('LLB', 'Ingineur'), ('BSC', 'Diplomingineur'), ('LLM', 'Professor'), ('Sonstiges', 'Very Important')], default='none', max_length=10),
        ),
    ]
