# Generated by Django 3.2.7 on 2021-09-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210921_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
                ('house', models.IntegerField()),
                ('postal', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.address', unique=True, verbose_name='adress'),
        ),
    ]
