# Generated by Django 3.2.8 on 2021-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='job',
            field=models.CharField(choices=[('l', 'Lead'), ('o', 'Other'), ('n', 'Not Spezified')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('n', 'Not Spezified')], default='n', max_length=1),
        ),
    ]
