# Generated by Django 3.2.8 on 2021-10-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20211010_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
